= 《Gradle in Action》阅读笔记

开始时间：20201123

== Part 1. Gradle介绍

== 1. 项目自动化介绍

=== 1.1. 如果没有项目自动化

* 用IDE做所有的事情
* 只能在我的机器上运行
* 代码集成是个灾难
* 测试过程异常缓慢
* 部署变成了马拉松

=== 1.2. 项目自动化的好处

* 防止人工干预 -- 软件开发过程中，能自动化的就应该自动化
* 创建可重复执行的构建
* 使得构建可移植 -- IDE只能在特定机器上使用，自动化任务应该从命令行执行

=== 1.3. 项目自动化的类型

只有一种项目自动化类型：根据需要自动化（On-demand）

* 按需构建
* 触发构建 -- 代码提交到版本控制时触发构建
* 定时构建 -- 设计定时器，周期性自动调度执行构建命令

了解了项目自动化的好处和类型之后，可以进一步讨论实现这些功能所需的工具了。

=== 1.4. 构建工具

自动化工具的目标：

* 可重复执行
* 可用性
* 可移植性
* 没有人工干预

而自己编写执行脚本，不容易实现可移植性，特别是从UNIX类系统到Windows类系统。

==== 1.4.1. 什么是构建工具？

自动化工具要完成的任务及顺序：

编译代码--拷贝类文件到特定目录--装配可交付物（ZIP文件）

有向无环图 --  directed acyclic graph（DAG）

* 节点 -- 代表任务
* 箭头 -- 代表依赖关系，一个任务的执行必须依赖前一个任务的正常结束

==== 1.4.2. 解构构建工具

理解构建工具定义的构建逻辑中各个组件之间的交互很重要，包括输入、输出的数据。

构建工具包含的的元素及职责：

* 构建文件 -- （build script）包含构建所需配置，定义外部依赖、完成任务的指令和它们的内部依赖
* 构建输入和输出 -- 源代码、类文件、交付物
* 构建引擎 -- 构建引擎处理构建文件，解决任务间依赖，建立要执行命令所需的整个配置，然后按顺序执行任务
* 依赖管理 -- 依赖管理用于处理构建文件中声明的依赖定义

=== 1.5. Java构建工具

* Apache Ant
* Maven

==== 1.5.1. Ant

提供的典型任务：

* 编译
* 单元测试
* 打包
* 创建文档
* 用于文件系统和归档操作的其他预定义任务，也可以自己扩展

ant通过XML来描述构建文件。不提供依赖管理，需要借助外部工具如Ivy等。

尽管ant很灵活，但它的缺点：

* 使用XML定义构建逻辑比较繁琐
* 复杂的构建逻辑导致很长的不可维护的构建脚本
* 没有提供任何构建项目的指南
* 未提供运行时环境的API
* 如果不使用Ivy很难管理依赖

==== 1.5.2. Maven

* 标准的目录层级
* 标准的构建生命周期
** 编译
** 单元测试和集成测试
** 装配工件（JAR文件）
** 部署工件到本地仓库
** 发布工件到远程仓库

生命周期中的每一步被成为 phase --阶段。每个阶段按顺序执行。

缺点：

* 提供的默认结构和生命周期可能不适合项目需要
* 编写自定义扩展过于笨重
* 早期版本（<2.0.9）的Maven自动更新它们的核心组件，导致构建不稳定

==== 1.5.3. 下一代构建工具的需求

* 富于表现力、声明式、可维护的构建语言
* 标准的项目层级和生命周期，但有完全的灵活性和可配置，以修改默认配置
* 易用、灵活实现自定义逻辑
* 支持多项目结构构建交付
* 支持依赖管理
* 良好的集成和迁移解决方案
* 重点关注可扩展性、高性能构建，解决长时间构建问题。

高级的的构建工具需要在灵活性和可配置规范之间达到一个平衡，以使用现代软件项目的需要。

== 2. 下一代构建工具 Gradle

主要内容：

* 理解Gradle与其他构建工具的区别
* 描述Gradle的特性集合
* 安装Gradle
* 编写、执行简单的Gradle脚本
* 命令行运行Gradle

Gradle使用Groovy中的特定领域语言（DSL）代替XML。它支持使用Java或Groovy编写自定义逻辑。

Gradle提供了自己实现的依赖管理。不但高度可配置，而且能够尽可能兼容已有的依赖管理基础设施（Maven或者Ivy）。Gradle不但能够管理外部依赖，还能够支持定义和组织多项目构建，管理模块间依赖。

=== 2.1. 为什么使用Gradle？

maven的限制过于严格。

==== 2.1.1. Java构建工具的进化

Ant和Maven的共同弱点：

* 构建逻辑必须使用XML来描述

XML很适合描述层级数据，但不适合表述程序流和条件逻辑。当构建脚本变得复杂时，维护构建代码将变成噩梦。

=== 2.2. Gradle特性集合

* 富有表现力的构建语言和深层次API
* Gradle即是Groovy
* 灵活的约定
* 强有力的依赖管理
* 可扩展的构建
* 轻松扩展
* 和其他构建工具集成
* 社区驱动和公司支持
* 附加特征 -- Gradle Wrapper，丰富的命令行选项

=== 2.3. 持续交付

构建源码只是软件交付过程中的一个方面。发布到生产环境以交付业务价值才是最终目标。

* 运行测试
* 构建分发
* 分析代码质量
* 发布到目标环境

持续交付参考资料：

《Continuous Delivery: Reliable Software Releases through Build, Test, and Deployment Automation》

==== 2.3.1. 从构建到部署全部自动化

部署管道 -- 容版本控制系统到生产环境的过程：

* 提交阶段
* 自动化验收测试阶段
* 人工测试阶段 -- QA人工验证
* 发布阶段 -- 交付最终用户或生产环境

本书主要关注Gradle在commit和自动化验收测试阶段，具体任务包括：

* 编译代码
* 运行单元测试和集成测试
* 执行静态代码分析、测试覆盖
* 创建分发
* 准备目标环境
* 发布交付物
* 执行冒烟测试和自动化功能测试

发布管理工具：Asgard

https://github.com/Netflix/asgard

在Netflix已被替换成Spinnaker

https://spinnaker.io


=== 2.5. 开始使用Gradle

----
task helloWorld << {
   println 'Hello world!'
}
----

错误提示：

`Could not find method leftShift() for arguments`

在4.x版本中，leftShift()已被弃用。

== 3. 构建一个Gradle项目

=== 3.2. 构建一个Java项目

Java plugin不只是编译和打包源代码，它还为项目建立一个标准布局，保证Java项目中的任务按正确顺序执行。

==== 3.2.1. 使用Java plugin

在build.gradle中添加Java plugin：

`apply plugin: 'java'`

只要一行就可以构建Java代码，Gradle会按照约定，到默认目录src/main/java下选择源文件。

==== 3.2.3. 配置和使用外部依赖

----
repositories {
    mavenCentral()
}

dependencies {
    compile group: 'org.apache.commons', name: 'commons-lang3', version: '3.1'
}

----

=== 3.3. Web项目

如果使用War plugin，就不需要再使用Java plugin，因为其扩展至Java plugin。但即使都指定也没关系，“apply plugin”是幂等（idempotent operation）的，一个plugin只会执行一次。

使用WAR插件之后，约定会在src/main/webapp路径下找web应用的资源

=== 3.4. Gradle wrapper

wrapper的核心功能是可以让一个机器在没有安装运行时环境的情况下运行Gradle构建脚本。其也可以确保构建脚本使用特定版本的Gradle来运行。

==== 3.4.1. 创建wrapper

wrapper创建后应该提交到版本控制系统。

执行gradle wrapper命令将使用当前版本的Gradle runtime生成wrapper文件。

==== 3.4.2. 使用wrapper

gradlew/gradlew.bat



== Part 2. 掌握基础

== 4. 构建脚本要点

内容概要：

* Gradle构建块和API
* 声明新任务、操作已有任务
* 高级任务技术
* 实现和使用任务类型
* 挂入构建生命周期
* 监听器实现

=== 4.1. 构建块

每个Gradle构建由三个基本构建块组成：

* projects
* tasks
* properties

每个构建必须至少包含一个project，进而包含一个或多个tasks。Projects和tasks暴露的属性可以用于控制构建。

==== 4.1.1. Projects

build.gradle中的一个project对应一个类实例org.gradle.api.Project

多项目构建中，一个项目可以依赖另一个项目。

==== 4.1.2. Tasks

org.gradle.api.Task

任务提供了更多的接口

==== 4.1.3. Properties

每个项目和任务实例都提供可访问的属性，如description、version。也可以自定义属性（声明一个可多次使用的变量）。

属性可直接通过gradle.properties配置文件注入，该文件放在<USER_HOME>/.gradle目录下或项目根目录下，如果在用户目录.gradle下，则所有项目都使用同一个属性文件。

其他声明属性的方法：

* 通过命令行选项 -P 声明项目属性
* 通过命令行选项 -D 声明系统属性
* 环境属性

==== 4.1.12 在buildSrc目录中构建代码

随着项目构建代码的增长，为了提高代码的可维护性，可以将构建代码统一放在根目录下的 buildSrc 子目录中。这些构建脚本代码甚至也可以打包供其他项目使用，或者为它们编写测试。

== Part 3. 从构建到部署

== Appendix A 命令行

== Appendix B Groovy基础知识

gradle格式的starter第三方项目：

https://github.com/ePages-de/restdocs-wiremock

kotlin
https://github.com/valiktor/valiktor/tree/master/valiktor-spring

https://github.com/Catalysts/structurizr-extensions