= 学习笔记

== 1. 《FreeBSD Mastery: ZFS》

20200913

*HAST*

High Availability Storage Technology（高可用存储技术），FreeBSD的分布式存储解决方案

在两台物理上隔离的系统之间以透明的方式，通过TCP/IP网络传输数据的高可用性框架。HAST可以看作通过网络进行的RAID1（镜像），类似于Linux平台上的DRBD存储系统。

Ref：_https://www.freebsd.org/doc/zh_CN/books/handbook/disks-hast.html

同步及复制模式：

* memsync 本地写操作完成，并且远程节点汇报已经收到数据时，便认为数据的写操作已经完成。（目前尚未实现）
* fullsync 只有本地写操作完成，并且远程的写操作也已经完成的情况下，才认为数据的写操作已经完成。最保险，但最慢
* async 本地写操作完成时，即认为数据已经写完。最快，但风险最大。（目前尚未实现）

HAST出现脑裂情况时，需要人工干预进行恢复。

*DRBD* 

Distributed Replicated Block Device 基于Linux平台的分布式同步复制存储系统。已实现为内核驱动。

Ref：_https://www.linbit.com/user-guides/_

_DRBD is traditionally used in high availability (HA) computer clusters, but beginning with DRBD version 9, it can also be used to create larger software defined storage pools with a focus on cloud integration._

== 2. The Clean Code Blog博客文章

20200914

Robert C. Martin

=== 2.1. Classes vs. Data Structures

* 对象：一组函数，以及函数操作的数据元素
* 数据结构：被一些函数操作的一组数据元素

二者互补，类似手和手套。


数据库概要设计与业务对象设计：

* 业务对象定了业务行为的结构
* 数据库概要定义了业务数据的结构

对象和数据结构受不同的约束限制。

类与数据结构的不同：

* 类使函数可见，使数据隐藏；数据结构使数据可见，使函数隐藏
* 类增加类型容易，增加函数困难；数据结构使得增加函数容易，但增加类型困难
* 数据结构导致调用者需要重新编译和部署；类将调用者隔离在重新编译和部署之外

ref: _http://blog.cleancoder.com/uncle-bob/2019/06/16/ObjectsAndDataStructures.html_

=== 2.2. Thought Police 思想警察

在一个有活力的、自由的公司、社区和社会中：

* You never punish bad ideas 永远也不要惩罚错误的观点
* Instead, you counter bad ideas with better ideas 而应该用好的观点去反驳错误的观点

如果一个公司因为表达观点而解雇了一个人，那么这个公司将会死去。因为表达观点变成了不可容忍，那么创造力、想象力、冒险精神，所有这些一个公司、社区和社会必备的东西就受到了压制：

**“如果有权力的人解雇了那些表达错误观点的人，那么除了掌权者以外，没有人会再表达观点。”**

ref: _http://blog.cleancoder.com/uncle-bob/2017/08/09/ThoughtPolice.html_

== 2. 97 Things Every Java Programmer Should Know

=== 2.4. 注意容器环境

老代码应用程序容器化有一定的危险性，因为老版本的JVM在Docker中运行可能做蠢事。

容器已经成为运行时打包机制。他们提供的好处是：

* 一定级别上的隔离
* 提高了资源的利用率
* 应用的跨不同环境部署能力
* 降低了应用与底层平台的耦合度

容器化能够使遗留Java应用和其运行环境在现代的基础实施上运行，但也带来一定的风险。

JVM ergonomics依据两个关键指标对JVM进行优化：CPU数量和可用内存。根据这些指标，JVM决定使用哪个垃圾收集器、如何配置、heap大小、ForkJoinPool大小等。

JDK 8 update 191版本之后增加了对Linux Docker容器的支持，允许JVM基于Linux cgroups去获取分配给容器的资源指标。而旧版本的JVM只能访问主机操作系统的指标，而不是容器的指标。容器运行时一般又只被分配主机资源的一部分，这样JVM就会基于不正确的指标去优化自己。

这就会导致不稳定的状况，容器可能被所在主机杀掉。

所以不推荐在Docker容器上运行老版本的JVM。如果实在要用，至少应该设置不超过分配给容器的资源。

=== 2.14. JVM上的并发

原始的JVM上只有并发模型。运行并行应用程序的需求很低，缺少多核处理器，限制了并发的优点。

*线程和锁*

现在，线程和锁已经太低级：难于使用；理解Java内存模型更难。即使能够正确应用lock功能，它也会影响线程的并行执行，进而降低应用程序的并行程度。

Java不支持分布式内存模型，所以不能跨多个机器进行多线程扩展，测试就更不可能了。

*分布式队列*

突破共享内存限制的最好方法是通过分布式队列来协调线程。消息传递代替了共享内存，也提高了解耦。队列很适合单项沟通，但可能会有延迟。

*Akka*


Akka创造了actor模型，由Scala编写的JVM并发实现。

每个actor是个对象，只负责操作自身状态。并发是通过actor之间的消息传递来实现的，所以可以看作是队列的一个更结构化的应用。

Actors可以分级组织，通过监督提供内置的容错和恢复功能。

Actors的确定：

* 无类型消息难与缺少模式匹配的Java配合使用
* 消息的不可变性无法在当前的Java中强制执行
* 构造起来不太方便
* 死锁仍然可能出现

*Clojure*

Clojure采用其内置的软件事务内存，将JVM堆内存转换成事务数据集合。像一个常用的数据库，数据通过乐观事务语义修改。当有冲突发生时，事务会自动重试。这种无锁方式的优点是可以排除显式同步时的很多问题。使用起来也比较容易。

但这种方法在有很多并发写操作的高并行化系统中效率较差。这种情况下，重试增加了消耗，性能也就变得不可预期。

*Java 8 lambdas*

Java 8 lambdas 促进了函数式编程在代码中的应用，actor模型通过阻止共享，减少了可变状态；而函数式编程提供可共享状态是因为它禁止可变性。

由纯的、无副作用的函数组成的并行代码化能够做到很小，但函数式程序的效率可能要比相同功能的命令式要低，并且有可能给垃圾收集器带来更大的负担。

Lambdas也出尽了响应式编程的应用，用于异步处理事件流。

对并发来说没有银弹，但有很多不同的选项可以权衡，应该根据具体问题选择合适的方案。

== 3. 《Domain-Driven Design Quickly》

软件设计方法：

* 瀑布模型
* 敏捷

瀑布模型的缺点：

* 大量、详细的前期设计
* 各角色之间没有反馈 -- 系统分析人员没有反馈给业务专家；开发人员没有反馈给系统分析人员

敏捷的缺点：

* 敏捷倡导简洁，但每个人对“简洁”都有自己的理解。
* 如果没有可靠的设计原则，持续重构将导致代码难于理解和修改
* 瀑布方法可能导致过度设计，而对过度设计的担心又可能导致另一个担心：害怕做一个深入、彻底的设计

DDD将设计与开发实践相结合，展示了设计与开发可以更好的合作，创造一个更好的解决方案。好的设计可以加快开发，来自开发的反馈又可以改善设计。

瀑布式设计有些过度，敏捷又太忽视设计。

*一种通用语言*

开发者、领域专家分别有自己的语言，领域驱动设计的核心原则是使用一种基于模型的语言。

Ubiquitous Language -- 团队在沟通、代码，所有沟通形式中使用同一种语言，保证其一致性。

== 4. 《Running Lean Iterate from Plan A to a Plan That Works》

=== 4.1. 介绍

==== 4.1.1. 什么是Running Lean？

Running Lean is a systematic process for iterating from Plan A to a plan that works, before running out of resources.

运行精益是一个系统化的过程，用于在资源耗尽之前，从A计划迭代到一个可行的计划。

== 5. 《The Kollected Kode Vicious》

Georage V. Neville-Neil 

一个专栏内容汇总出版的一本书，采用对话形式，描述软件开发方面的各种小故事，开发语言的选型、开发习惯的对比..

*1.3 Coded arrangement*

If you want people to use your library, then you need to find out why they’re reaching around it and try to address their needs. The library isn’t there for you; it is there for them.

如果想让别人使用你的库，你需要找出人家绕过你的库的原因，并解决它们的需求。库不是为你存在，而是为使用者存在。

*1.15 Linguistically Lost*

关于开发语言的选择。

提到了Brian W. Kenighan 和 Rob Pike合著的《The Practice of Programming》是KV必读的书。该书讲述了如何针对不同的应用场景、特定的问题选择合适的开发语言和开发工具。

*2.2 How Much + in C++？*

选择开发语言需要考虑的因素：

* 团队成员里，哪个语言经验最丰富，比例最高？
* 目标应用是否需要所选开发语言的某个特性？
* 应用是否使用了其他应用或库提供的服务，而且是使用其他语言编写的，并且难以使用和调试？

在代码和所使用的库中间创建一个夹层的方法会更容易引入bug，所以应该尽量避免（in-laws）。

*4.3. Protocol Design*

An implementation should be conservative in its sending behavior, and liberal in its receiving behavior.
-- J.Postel
(一个实现应该在发送时保守，在接收时宽容。)

*5.5. Review the Design*

A software design review is intended to answer a basic set of questions:

1. How does the design take inputs and turn them into outputs?

2. What are the major components that make up the system?

3. How do the components work together to achieve the goals set out by the design?

*5.18 Books*

__You don’t have to burn books to destroy a culture. Just get people to stop reading them. -- Fahrenheit 451 __

计算机相关的书越来越多，但好书却是相对固定不变的。

Sturgeon's law: __90 percent of everything is crap.__

VK推荐的值得一读的数：

* The Elements of Style by William Strunk -- 计算机书的内容必须通俗移动，不要使用行话，不要使用太长的句子。作者要使读者明白的不是作者有多高明，而是作者要讲述的主题的内涵。
* The Art of Computer Programming by Donald Knuth -- 当有关于算法的问题或者想优化一些代码时，总是能在这套书中找到答案，不一定要从头到位的读。
* The Art of Computer Systems Performance Analysis: Techniques for Experimental Design, Measurement, Simulation, and Modeling by Raj Jain
* Anything written by Richard Stevens including, but not limited to, TCP/IP Illustrated Volume 1 and 2
** UNIX Network Programming, Volume 1 The Sockets Networking API, 3rd Edition by W. Richard Stevens, Bill Fenner, Andrew M. Rudoff (z-lib.org).pdf
** UNIX Network Programming Interprocess Communications by W. Richard Stevens (z-lib.org).pdf
** TCPIP详解 卷3：TCP事务协议、HTTP、NNTP和UNIX域协议 by W.Richard Stevens (z-lib.org).pdf
* The Practice of Programming by Kernighan and Pike
* Hacker's Delight by Henry S. Warren Jr
* Unix and Linux System Administration Handbook by Evi Nemeth

* C. Northcote Parkinson, who wrote a book about management (Parkinson’s Law and Other Studies in Administration, Ballantine Books, 1969). 

== 6. 《The Design and Implementation of the FreeBSD Operating System》

Georage V. Neville-Neil 

书中第11章提到了网络文件系统的性能优化方法 -- 采用客户端缓存，但客户端缓存又可能存在数据的延迟更新等问题。

这本书讲述了FreeBSD操作系统的设计原则、针对问题的解决方案等，可以详细阅读。

== 7. 《Dapper, a Large-Scale Distributed Systems Tracing Infrastructure》

Google关于分布式系统追踪基础设施的论文。

== 8. 《An Introduction to the Analysis of Algorithms》

Robert Sedgewick

书中提到的相关阅读书籍：

* The Art of Computer Programming
* Introduction to Algorithms
* Analytic Combinatorics

这本书可以作为上述几本书的一个补充阅读。

== 9. 《Learning in Depth》

深入学习的重要性，方法。

知识应该深入学习，不应该只学习表面部分，通过深入学习才能更理解知识的深层内容，同时也会扩展学习到其他很多知识。如果只是学习表层，会导致自以为学会了很多，实则很少。

* 学的越深的人会越觉得自己的无知；
* 学的越少的人会越觉的自己什么都懂，盲目的自信；

== 10. Gradle笔记

=== 10.1. 生成文档和源代码包

javadoc {
    options.encoding('UTF-8')
}

java {
    withJavadocJar()
    withSourcesJar()
}

=== 10.2. Gradle配置多环境yaml占位符自动替换

参考 《Gradle User Manual Version 6.7.1》

Migrating Maven profiles and properties

== 11. Maven将第三方jar包发布到远程仓库

命令：*mvn deploy:deploy-file*

设置远程仓库连接账号：

```
<server>   
<id>central</id>   
<username>admin</username>   
<password>admin123</password>   
</server>
```

发布命令：

```
mvn deploy:deploy-file -DgroupId=<group-id> \
  -DartifactId=<artifact-id> \
  -Dversion=<version> \
  -Dpackaging=<type-of-packaging> \
  -Dfile=<path-to-file> \
  -DrepositoryId=<id-to-map-on-server-section-of-settings.xml> \
  -Durl=<url-of-the-repository-to-deploy>
```

```
mvn deploy:deploy-file -DgroupId=com.sungness.test \ -DartifactId=target \
-Dversion=1.0.0 \
-Dpackaging=jar \
-Dfile=/path/to/target.jar \
-Durl=http://ip:port/nexus/content/repositories/releases \
-DrepositoryId=releases
```

== 12. CentosOS 7.8安装ruby25、cas博客文档编译

```
# 1. Install a package with repository for your system:
# On CentOS, install package centos-release-scl available in CentOS repository:
$ sudo yum install centos-release-scl

# On RHEL, enable RHSCL repository for you system:
$ sudo yum-config-manager --enable rhel-server-rhscl-7-rpms

# 2. Install the collection:
$ sudo yum install rh-ruby25

# 3. Start using software collections:
$ scl enable rh-ruby25 bash
```

```
cd /home/test1/
git clone https://github.com/apereo/apereo.github.io.git
cd apereo.github.io/
gem install bundler:1.16.1
sudo yum install rh-ruby25-ruby-devel
bundle install

```

安装王ruby-devel后，用root身份再运行bundle install

构建并启动站点：

bundle exec jekyll serve --host=192.168.142.137 --incremental

指定host为暴露的IP地址。



== 14. Swagger框架

springfox + Knife4j

在Knife4j 3.0版中，后端Java代码和ui包分离为多个模块的jar包,以面对在目前微服务架构下,更加方便的使用增强文档注解(使用SpringCloud微服务项目,只需要在网关层集成UI的jar包即可,因此分离前后端)

https://xiaoym.gitee.io/knife4j/documentation/description.html

== 15. 《Functional Programming in Java》

=== 前言

从语言角度来说，Java只是支持函数式编程，但它不是为函数式编程而生。最适合函数式编程的语言是 Haskell、Scala。但从公司或项目角度来说，如果无法决定在项目中使用哪种语言，必须接受Java的话，那就有必要学习Java中的函数式编程方法和思维。

=== 关于本书

* imperative paradigm 命令式范式
* functional paradigm 函数式范式

没有所谓的函数式语言，只有哪种语言对函数式编程更友好。

== 16. 单元测试

单元测试的学习清单：

* JUnit in Action, Third Edition
* Testing Java Microservices
* Working Effectively with Unit Tests
* xUnit Test Patterns
* Test Driven Development By Example by Beck, Kent

《Testing Java Microservices》书中 3.1 中提到 _sociable unit test_ 和 _solitary unit test_ 概念来源于《Working Effectively with Unit Tests》 一书；

3.1.2 中提到的 test double 概念来源于 《xUnit Test Patterns: Refactoring Test Code》一书。

=== 16.1. 引申阅读

《Test Driven Development》作者Kent Beck的另一本书《Implementation Patterns》讲述如何通过代码沟通：

* 第一，编程时保持意识清醒
* 第二，承认其他人的重要性
* 第三，在实践中示范实现模式

其书中又提到内容介于 Design Patterns 和 Java语言之间。并且本书的实现模式中为解决并发问题。推荐阅读《Java Concurrency in Practice》一书。

《Java Concurrency in Practice》主要讲述一套设计规则和思维模型，用于并发应用程序的开发，关注的是高级层面（设计层面）的策略和模式。（很多其他并发方面的书关注的是底层机制）

=== 16.2. TDD 的三个简单步骤

* 为下一步要添加的功能编写一个测试程序
* 实现功能代码，直到测试通过
* 重构新老代码，使得达到良好的结构

循环使用这三个步骤。这样做的好处：

* 写出的代码总是自测试的
* 先思考测试，强迫你先思考代码的接口

在具体实践过程中，第三部经常被忽略。重构代码，保证其整洁性，是这个过程中关键的一部分，否则代码会变得很凌乱。

=== 16.3. C/C++单元测试

* Google C++ Testing Framework（https://github.com/google/googletest）

open regression frameworks：

* Boost unit test framework
* CppUnit.

相关文章：

* https://developer.ibm.com/technologies/systems/articles/au-googletestingframework
* https://www.ibm.com/developerworks/aix/library/au-ctools2_cppunit/index.html
* au-ctools2_cppunit-pdf.pdf
* http://cppunit.sourceforge.net/doc/cvs/cppunit_cookbook.html
* https://netbeans.org/kb/docs/cnd/c-unit-test.html
* http://sourceforge.net/projects/cunit/

测试框架：

* packages/cppunit-cvs-repo-archive.tar.bz2
* packages/CUnit-2.1-3.tar.bz2


《Unit Test Frameworks》



== 18. Gson 和 springfox 冲突问题的解决

Spring Boot引入Gson自动化配置，导致springfox的API接口返回的json数据外面多包了一层 value，解决方案如下：

https://stackoverflow.com/questions/30219946/springfoxswagger2-does-not-work-with-gsonhttpmessageconverterconfig/30220562#30220562

springfox官方文档：

Caveat to using the library is that it depends on Jackson for serialization, more importantly the `ObjectMapper`. A
good example of where this breaks down is the following http://stackoverflow.com/a/30220562/19219[issue when using Gson serialization]

== 19. 《Inffrastructure as Code》

Organizations can’t choose between being good at change or being good at stability. They tend to either be good at both or bad at both.

Normalization of Deviance：

《The Challenger Launch Decision》 作者: Diane Vaughan 
出版社: University Of Chicago Press

《The Visible Ops Handbook》 (IT Process Insti‐ tute)
TDD/CI/CD

== 20. Microservices: Up and Running

微服务下的分布式事务解决方案，传统的ACID已不再适用，而采用Sagas更合适：

“With sagas, every step of a transaction not only performs the required action for that step, but it also defines a compensating action that should execute if we need to roll back the transaction due to a later failure. A pointer (e.g., discovery information on a queue) to this compensating action is registered on a routing slip and passed along to the next step. If one of the later steps fails, it kicks off execution of all compensating actions on the routing slip, thus “undoing” the modifications and bringing the system to a reasonably compensated state.”

Excerpt From: Ronnie Mitra. “Microservices: Up and Running.” Apple Books. 

应用Sagas，事务的每一步不仅仅执行需要的操作，它还定义一个补偿操作，当在后来的失败中需要回滚事务时执行。补偿操作被注册到一个路由表上，被传递到下一步。如果之后的某一步失败了，它就开始执行路由表上的每一个补偿操作。因此“撤销”修改，并将系统置于一个合理的补偿状态。

*Sagas与ACID事务并非直接等效*

当分布式事务回滚时，Sagas不承诺系统将恢复到初始状态。而是在部分完成的事务撤销之后，达到一个可接受的合理状态。

reasonable state

举例：

当用户预定座位，支付完成后，如果预定失败，则支付服务将收到退款补偿请求，为用户退款；由于支付类型的不同，退款可能不是立即处理，所以系统不能立即恢复到初始状态，但最终，客户会拿回他们的钱。也就是说，客户会看到付款和退款两条记录。（传统的ACID事务，用户看不到回滚记录）

*Saga中事件的顺序是有意义的*

Saga中的事件顺序很重要，应该认真构思。通常，将补偿比较麻烦的步骤放在事务的结尾比较合适。例如，如果业务规则允许，将“通知”放在处理过程的最后，可能使我们不必发送大量的更正消息。这样，当事务开始发送警告时，我们将知道前面的步骤已经成功了。

== 21. CKAD Kubernetes应用开发认证

CKAD -- Certified Kubernetes Application Developer

《Certified Kubernetes Application Developer Study Guide》

学习这本书之前，最好先阅读两本基础入门书：

* 《Kubernetes Up & Running》
* 《Kubernetes in Action》

CKA -- Kubernetes管理员认证

== 22. Entity、Value Object、DTO 

概念、来源、应用场景和方法

=== 22.1.《微服务架构模式》中 Entity、Value object的定义：

* Entity —- 带有一个持久化唯一标识的对象。两个实体即使有相同的属性值，也是不同的对象。在Java EE应用中，类使用 JPA 注解 @Entity 的类通常是 DDD 实体。
* Value object —- 是一个值的集合的对象。两个值对象的属性值相同，可以互换使用。值对象的一个例子就是 Money 类，它由货币和金额组成。

=== 22.2.《Patterns of Enterprise Application Architecture》

Chapter 15: Distribution Patterns

* Remote Facade
* Data Transfer Object

==== Remote Facade

Granularity -- 粒度 是应用 Remote Facade 时最难的一个问题。

最大的错误是在 Remote Facade 中放置了领域逻辑。Remote Facade 中不应该有领域逻辑（domain logic）

任何一个facade 都应该是 thin skin ，只有最小的职责。

service层没必要使用 Data Transfer Objects（DTO），它可以直接返回领域对象给客户端。

什么时候使用 Remote Facade ？

需要远程访问一个细粒度对象模型时，就应该使用 Remote Facade。最常见的应用场景时展现层和Domain Model之间。

如果只是在单个进程内访问，则不需要使用Remote Facade。

==== Data Transfer Object

An object that carries data between processes in order to reduce the number of method calls.

在处理过程中传递数据的对象，目的是为了减少方法调用。

How It Works

数据传输对象 通常是令人生厌的。它仅仅是一堆带有getter和setter方法的字段。允许在一次网络调用过程中移动一组信息，这是分布式系统中必不可少的技巧。

*如何使用 DTO*

* 序列化时最好使用文本形式（Json/XML），二进制形式的序列化在反序列化时，如果增加或删除字段，容易导致失败；
* 直接使用数组作为DTO的缺点：数组索引会使代码难以理解
* 最好的集合是使用字典（map），这样可以使用有意义的字符串作为keys。但字典又有一个问题就是没有明确的接口和抢类型。当没有现成的DTO生成器时，可以临时使用字典；
* 当使用生成器时，最好使用一个接口，特别是当要考虑将其用在不同的组件之间当作通信协议使用时。

*从领域对象装配DTO*

DTO不知道如何与领域对象沟通，因为它要部署在连接的两端。所以，DTO不应该依赖领域对象。领域对象也不应该DTO，因为当修改接口格式时，DTO的结构也会发生变化。所以应该保持领域模型不依赖于外部接口。

这就需要创建一个分离的assembler（装配器）对象，负责从领域模型创建DTO，以及从DTO更新模型。装配器是 Mapper 的一个例子，在DTO和领域对象间进行映射。

多个装配器可以共享同一个DTO。不同场景下不同的修改含义，使用相同的数据。

分离装配器的另一个原因是 DTO 可以很容易通过简单的数据描述自动生成。而自动生成装配器就比较困难。

*何时使用DTO*

当在两个过程中的一个方法调用需要传输多个数据条目时，就需要使用DTO。

有几种替代DTO的方案（虽然不怎么好）：

* 不使用对象，而使用带有多个参数的set方法或者可以传递多个引用参数的get方法。问题是像Java这种语言只允许返回一个对象，所以这种方法即使可以用于更新，但在不使用回调方法时，无法用于取回信息
* 另一种替代方案是使用类似string形式的展现方式，不使用接口。问题是所有的代码都会和这个string representation耦合到一起。而使用显示接口可以隐藏背后的细微展现形式，如果想改变字符串或者替换成二进制结构，不需要修改任何东西。

当想在两个组件之间使用XML通信时，特别值得创建DTO。XML DOM操作起来很麻烦，使用DTO对其进行封装，并且DTO很容易生成。

另一个常见的目的是将DTO作为一个通用数据源，用于不同层的组件。每个组件对DTO做一些修改，然后将其传递给下一层。

==== Value Object

A small simple object, like money or a date range, whose equality isn't based on identity.

小的简单对象，例如 money 或者 date 范围，判断是否相等时不依赖唯一标识。

由于有各种个样的对象系统，所以有必要区分以下引用对象和值对象。值对象通常比较小，类似很多非纯面向对象语言中的基本类型。

值对象如何工作？

引用对象和值对象的关键区别在于如何处理相等问题：

* 引用对象使用唯一标识作为判断是否相等的基础 -- 可能是编程系统中的唯一标识，例如OO编程语言中的内置唯一标识，或者是某一类ID数字，例如关系型数据库中的主键。
* 值对象基于类中的字段值来判断是否相等。因此，如果两个日期对象，如果它们中的年月日的值均相同，那么两个日期相同。

最好将值对象做成不可变的，一旦创建，任何字段不再修改。这样可以避免 aliasing bugs。当两个对象共享同一个值对象时，可能会出现别名bug（其中一个所有者修改了它的值）。

*何时使用值对象*

当不使用唯一标识判断相等时，可以使用值对象。任何容易创建的小的对象都值得考虑使用值对象。

名字碰撞：有些J2EE社区将值对象等同于DTO，这个需要注意。

== 23. 设计模式、架构模式的相关阅读资源

* 《微服务架构模式》 -- 适合微服务架构的各种模式
* 《Patterns of Enterprise Application Architecture》 -- 适合企业应用开发的各种模式，提到了值对象、DTO、实体等。
* 《DDD 领域驱动设计》 -- 领域模型
* 《实现领域驱动设计》
* 《设计模式》
* 《Head First Design Patterns》

《领域驱动设计》中提到了值对象（Value Object）、实体（Entity）、DTO，与《Patterns of Enterprise Application Architecture》结合阅读，Martin Fowler的这本书中解释的更详细、清楚。

== 24. Angular JS

=== 24.1. 本地环境和工作空间设置

基础依赖：

* Node.js
* npm 包管理器

*安装 Angular CLI*

----
npm install -g @angular/cli
----

*创建工作空间并初始化应用*

----
ng new my-app
----

*运行应用*

----
cd my-app/
ng serve --open
----

默认地址： http://localhost:4200/

== 25. Git for Teams

=== Chapter 3. 分支策略

==== Conventions

*主干分支开发*

最简单的分支策略就是主干分支方法。这种策略下，只使用很少的分支。开发者持续将工作提交到单一的中心分支 -- 它必须始终是准备发布状态。也就是说，主干分支应该只包含测试通过的代码，而且应该永远不会被破坏。

directed acyclic graph 有向无环图

使用鼓励定期集成的分支策略的一些好处：

* 整个项目过程中不会有太多分支。减少冲突
* 提交到代码库中的commit相对较小。如果出现问题，可以快速回退。
* 更少的紧急修复，因为保存进主干分支的任何代码都是可部署的。

缺点：

* 前提是假设主干分支包含的必须是可部署代码。如果团队没有一个测试基础设施，那么假设代码不会出错的风险很大，特别是当项目变得越来越复杂时。
* 部署的概念更适合可自动加载到用户设备上的网站类应用。不太适合需要重新下载、安装的应用。
* 

*按功能分支部署*

为了克服单个分支策略的局限，可以额外引出两种类型的分支：

* 功能分支
* 集成分支

技术上来说，它们并非不同的分支，只是提交的工作内容的类型不同。

在按功能分支部署的策略下，所有新工作都在一个功能分支完成，它应该尽量小到恰好包含一个完整的idea。

*GitHub Flow*

GitHub 项目分支使用流程：

* master分支中的任何代码都是可部署的
* 当开发新功能时，从master创建一个有描述性名称的分支（ie：new-oauth2-scopes）
* commit到本地分支，并经常性的将开发工作推送到服务器上的相同分支
* 当需要反馈或帮助时，或者认为这个分支已经准备好合并，打开一个pull request
* 当代码经过审查或某个人对这个功能签字确认后，可已将其合并到master
* 一旦它被merged并推到master，你可以并且应该立即部署

== 26. shell

=== 26.1. shell中条件判断的两种方式

* [] -- which is available in many different versions of the Bourne shell.
* [[]] --  The second version is identical to the first except that word splitting and pathname expansion are not performed on the words within the brackets.

* [ condition ] -- 括号前后的空格是必须的

ref: Learning the bash shell, 3rd Edition

==== 26.1.1. 字符串比较

* str1 = str2  匹配
* str1 != str2 不匹配
* str1 < str2  小于
* str1 > str2  大于
* -n str1      str1 非空，长度大于0
* -z str1      str1 为空，长度为0

==== 26.1.2. 文件属性检查

* -a file  -- 文件存在返回true
* -d file  -- 文件存在并且是路径返回true
* -e file  -- 文件存在；与 -a 相同
* -f file  -- 文件存在，并且是普通文件，不是路径或其他特殊文件
* -r file  -- 有读取文件的权限
* -s file  -- 文件存在并且非空
* -w file  -- 有写文件的权限
* -x file  -- 有执行文件权限，或者路径有搜索权限
* -N file  -- 文件在最后一次读取之后已被修改
* -O file  -- 你自己的文件
* -G file  -- 文件所属group ID与你的匹配
* file1 -nt file2  -- file1 比 file2 新
* file1 -ot file2  -- file1 比 file2 旧

==== 26.1.3. brace expansion 与区间遍历

借助 brace expansion 功能针对区间 [begin, end]进行遍历

先将中括号[1, 5]转换成大括号格式：{1..5}，再利用eval对其进行遍历：

----
src_str="[1,5]"
src_str=`echo $src_str | sed 's/\[//' | sed 's/\]//' | sed 's/, */../'`
dest="echo {$src_str}"
for num in $(eval $dest); do
  echo "num=$num"
done
----

==== 26.1.4. bash脚本中函数返回值

bash中不能使用return作为返回值的命令，只能通过echo输出要返回的内容，然后由调用方捕捉输出的内容：

----
fun1() {
  echo "fun1_return"
}

res=$(fun1)
echo "res=$res"
----

== 27. UML

《UML for Java Programmers》

=== 27.1 概述

UML -- Unified Modeling Language

用于绘制软件概念的示意图。

三个应用场景：

* 一个问题领域的的示意图，对应级别 Conceptual 概念的
* 目标软件设计，对应级别 Specification 规格说明
* 已完成软件的实现，对应级别 Implementation 实现

Specification 和 Implementation 级别的示意图与源代码有很强的相关性。Specification要转换成源代码，而Implementation用于描述已存在的源代码。必须遵循严格的语义规则。

Conceptual 级别的示意图与源代码没有太强的联系，它们与人类语言更接近。用于描述人类问题领域的抽象概念。不需要遵循严格的语义规则。

== 28. Cloud Native Go

Chapter 11 Observability

Logging
Logging is the process of appending records of noteworthy events to an immuta‐ ble record—the log—for later review or analysis. A log can take a variety of forms, from a continuously appended file on disk to a full-text search engine like Elasticsearch. Logs provides valuable, context-rich insight into application- specific events emitted by processes. *However, it’s important that log entries are properly structured; not doing so can sharply limit their utility.
We’ll dive into logging in more detail in “Logging” on page 387*.

*Logging*

log -- an immutable record of events.

Better Looging Practices

* maximizing the quality, and minimizing the quantity.
* shouldn't log sensitive business data or personally identifiable information
* logs should be treated as a stream of events, and should be written, unbufferer, directly to stout and stderr.
* structure events for parsing

*structured log elements*

* time -- a timestamp
* level -- level of importance for the log event, INFO, WARN, ERRO
* One or more contextual elements -- method, error, message, duration...

the structured log form is easier, faster, and cheaper to extract meaning from, nad the results are far easier to search, filter, and aggregate.

*Tip*

Don't use line breaks in your log events if you can help it.

== 29. Cloud Native

=== 29.6. Best Practices

*Logging*

* Use a Unified Logging System
* Use Correlation IDs -- unique CID through all services, pinpoint where the failure occured.
* Include context with Log Entries -- all execption handling, retry attempts, service name or ID, image version, binary version..
* Common and Structured Logging Format -- all components use a common and structured logging format. Use same time zone.

== 30. spring-boot-reference Logging

== 4.4. Logging

Spring Boot 内部使用 Commons Logging，但底层的log实现是开放的，并提供了以下默认配置实现：

* Java Util Logging
* Log4J2
* Logback

如果使用Starters，则自动使用 Logback。项目中可直接使用 SLF4J。

=== 4.4.1. 日志格式

Spring Boot 默认日志输出格式：

----
2019-03-05 10:57:51.112  INFO 45469 --- [           main]
  org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache
  Tomcat/7.0.52
----

包括以下条目：

* 日期和时间 -- 精确到毫秒，方便按时间排序
* 日志级别 -- ERROR, WARN, INFO, DEBUG, TRACE
* 进程ID
* --- 分隔符，用于区分真正日志信息的开始
* 线程名 -- 方括号括起来的字符串，控制台输出时可能被截断
* 日志输出者名称 -- 通常是输出日志的类名（包名部分通常是缩写）
* 日志消息 -- 程序中输出的具体日志描述信息

*Tip*

Logback中没有FATAL级别，其映射到了ERROR。

=== 4.4.2. 控制台输出

默认的日志配置是将消息输出到控制台。默认情况下，ERROR，WARN，INFO三个级别的消息会被记录日志。也可以通过在命令行指定 --debug 参数来指示应用输出debug日志。

> java -jar myapp.jar --debug

可以指定 --trace 参数来开启trace模式，也可以在properties中设置trace=true

*Color-coded Output*

使用 spring.output.ansi.enabled 配置开启控制台日志带颜色的格式化输出

> spring.output.ansi.enabled=ALWAYS

=== 4.4.3. 文件输出

Spring Boot日志默认输出到控制台，如果需要输出到日志，需要设置 logging.file.name 或者 logging.file.path属性。

如果指定的是路径，那么直接写到spring.log文件中，大小达到10MB时会轮换新文件。可以设置文件大小、历史文件的保留天数、文件总大小等参数，也可以设置在应用启动时清除历史文件。

=== 4.4.4. 日志级别

logging.level.<logger-name>=<level>可设置的级别包括：

* TRACE, DEBUG, INFO, WARN, ERROR, FATAL, or OFF. 

----
  logging.level.root=warn
  logging.level.org.springframework.web=debug
  logging.level.org.hibernate=error
----

=== 4.4.5. 日志分组

----
 logging.group.tomcat=org.apache.catalina, org.apache.coyote, org.apache.tomcat
 logging.level.tomcat=TRACE
----

=== 4.4.6. 自定义日志配置

== 31. The Go Programming Language

Go语言特殊的点：

1. 声明变量时有多种写法

* var a int -- 只声明为int类型，默认值为0
* var a = 10 -- 通过右侧值类型确定 a的类型为int
* a := 10 -- 声明加赋值，简写形式
* 同时声明或赋值多个变量 -- a, b := 1, 2 这种写法a和b必须有一个是新声明的变量，否则需要直接使用 a, b = 1, 2

2. 方法内的变量只对方法内可见，方法外的变量如果开头字母小写只对当前包可见，如果大写对其他包也可见

3. 也有指针概念，但和c语言中的指针的区别是没有指针算数运算

4. go语言中没有空指针概念，所有变量都是有默认值的，整型为 0， 布尔型为 false，字符串型为空字符串，接口或指针类型的默认值为 nil

5. go语言中函数可以返回内部局部变量的地址（指针类型）

6. 指针类型也可以比较，只有两个指针指向同一个变量地址时才相等

=== 2.6 包和文件

包能够隐藏信息，用于控制哪些名字对包以外是可见的，一个简单的规则就是对包以外可见的标识符首字母大写。

2.6.2 Package Initialization 没太看懂

=== 2.7. Scope

* 声明的可见范围是编译期属性
* 生命周期（lifetime）是执行期变量可被其他部分引用，是运行时属性

*lexical blocks*

*universe block*

Go中的正常做法一般是在 if 块处理错误并返回，而成功执行路径不缩进。

=== 3. Basic Data Types

Go中的四种类型：

* basic types -- 数值、字符串、boolean
* aggregate types -- 数组、结构体
* reference types -- 指针、slices、maps、函数、channels
* interface types


== 32. Programming Rust

Rust语言语法的特点：

* while或if条件部分代码两边不需要小括号
* let 声明局部变量时可以不明确指定类型，而由所赋的值来自动推断出来
* 如果函数体结尾最后一行以表达式结束，并且没有分号，表示表达式的值为函数的返回值，不用加return（挺奇葩）；只有在程序中间位置要返回时才需要显式使用return

命令行打开浏览器浏览Rust标准库帮助页面：

 rustup doc --std

Rust语言的库引入借鉴了C++语言中的use namespace 命名空间的方式。

所有Rust函数都是线程安全的

*Concurrency 一节没看懂* （Chapter 2. A Toour of Rust）

[dependencies] 中的 crates 版本号如果只写一位（如：1），表示Cargo将使用2.0以前的最新版本。

如果程序在1.2版本测试通过，那么通常在1.3， 1.4版本下都应该能够正常工作；但2.0可能会引入不兼容的变化。

当执行程序报 Blocking waiting for file lock on package cache 并挂起时的解决办法：

rm ~/.cargo/.package-cache

删除该缓存文件。

如果

__rustup component add xxx --toolchain stable-x86_64-apple-darwin__

这种命令无法执行，开启代理后，执行 . ~/.profile，加载http_proxy/https_proxy